Streamline Sauce Labs API interactions
Every request now goes through general-purpose `saucelabs-api` command
which, by default, dumps the data in line-based format suitable for
parsing on the command line. If `--raw` is passed, raw JSON is returned
instead.

diff --git a/script/saucelabs b/script/saucelabs
--- a/script/saucelabs
+++ b/script/saucelabs
@@ -19,16 +19,35 @@ trap "kill $sauce_pid" INT EXIT
 while [ ! -f "$sauce_ready" ]; do sleep .01; done
 rm -f "$sauce_ready"
 
-job=$(./script/saucelabs-start "http://localhost:$port/test/test.html")
+job="$(./script/saucelabs-api --raw "js-tests" <<JSON
+  { "public": "public",
+    "build": "$TRAVIS_BUILD_NUMBER",
+    "tags": ["$TRAVIS_PULL_REQUEST", "$TRAVIS_BRANCH"],
+    "tunnel-identifier": "$TRAVIS_JOB_NUMBER",
+    "platforms": [["$SAUCE_PLATFORM", "$SAUCE_BROWSER", "$SAUCE_VERSION"]],
+    "url": "http://localhost:$port/test/test.html",
+    "framework": "mocha"
+  }
+JSON
+)"
 
-while true
-do
-  result=$(echo "$job" | ./script/saucelabs-status)
-  [[ $result == *"\"completed\": true"* ]] && break
+while true; do
+  result=$(./script/saucelabs-api "js-tests/status" <<<"$job")
+  grep -q "^completed: true" <<<"$result" && break
   sleep 1
   echo -n "."
 done
 
-echo -n ""
+echo
 
-echo "$result" | ./script/saucelabs-result
+awk '
+  /result\.tests:/ { tests+=$(NF) }
+  /result\.passes:/ { passes+=$(NF) }
+  /result\.pending:/ { pending+=$(NF) }
+  /result\.failures:/ { failures+=$(NF) }
+  /\.url:/ { print $(NF) }
+  END {
+    printf "%d passed, %d pending, %d failures\n", passes, pending, failures
+    if (failures > 0 || tests != passes + pending) exit 1
+  }
+' <<<"$result"
